### PR TITLE
INFRA-2634: Update ctlsettings to 0.3.0 for ALB Migration

### PR DESCRIPTION
**Pull request by dc3788**
Update to ctlsettings 0.3.0 which include changes for AWS migration.

### CODE REVIEW

**Comment by Evan-CTL** [comment]
Looks good! Running fine on my system

**Review by Evan-CTL — APPROVED** [review]

**Review by Evan-CTL — COMMENTED** [review]
This file is fine, but django_markwhat needs to be added to INSTALLED_APPS in the django settings.

**Comment by dc3788** [comment]
@Evan-CTL, I did not see that issue on my local.  Also I didn't see `django_markwhat` in the `requirements.txt` file.  Is this something we should add?

**Comment by ndittren** [comment]
This looks fine. The template syntax error is something we run into with the initial ctlsettings migration so this update shouldn't break that. I put up a separate PR here to address that issue: https://github.com/ccnmtl/worth2/pull/2631

**Comment by Evan-CTL** [comment]
> @Evan-CTL, I did not see that issue on my local. Also I didn't see `django_markwhat` in the `requirements.txt` file. Is this something we should add?

It's _Line 91_ in requirements.txt `django-markwhat==1.6.2`, but if no one else is getting an error it might be something to do with my local setup.

**Pull request merged**
