### PR TITLE
Attach SSNM's Supporter to User instead of Participant - PMT #98027

### PR DESCRIPTION
**Pull request by nikolas**
I'm moving the relation on Supporter from Participant to a normal
django User, so all authenticated users can use the SSNM activity.

### CODE REVIEW

**Comment by thraxil** [comment]
Is it really safe to deploy this? The migration adds a not-null ForeignKey field, which means that if the database contains any existing Supporters, it's going to hit constraint violations and fail.

**Comment by nikolas** [comment]
Well, that's why I made this data migration as a dependency of the column migration, which deletes all the existing Supporters: https://github.com/ccnmtl/worth2/pull/58/files#diff-7a1ded4d72063b86865b1435aa257621R7

I would really prefer the Supporter's `user` field to be non-null, since having a Supporter with no user attached doesn't make any sense, and shouldn't happen.

**Comment by thraxil** [comment]
But that means it's deleting a bunch of user data in production? That seems like the wrong way to approach a migration.

The safe approach is to do a migration that adds the foreign key as a nullable, change the code to write/update both anywhere it's changed, then a data migration to backfill the empty rows, then a migration to switch it to a non-null, change the code to start using the new field, and then a migration to remove the old field.

**Comment by nikolas** [comment]
Ah I see. That makes sense - I'll make this field nullable then for this PR.

**Comment by nikolas** [comment]
I've updated the commit, which now just includes the column migration, and allows the new `user` field to be `null`.

It looks like the migration should go smoothly - I just tested out this migration on the prod db backup locally.

**Pull request merged**
