### PR TITLE
Participant sign-in form updates

### PR DESCRIPTION
**Pull request by nikolas**
* Removed my non-standard RawModelChoiceField, RawModelChoiceIterator
form overrides, instead getting this functionality with the
get_participant templatetag.

* This includes a performance improvement to
Participant.highest_module_accessed, to improve the sluggish
loading time on the sign-in page. I was able to remove all
the test skips as a side effect, since this method no longer
uses `.distinct()`.

* Sign-in form now saves selected participant and destination
when displaying a validation error (PMT #100762)

Addressing PMTs #100796, #100797, #100762

### CODE REVIEW

**Comment by sdreher** [comment]
Nik - reviewing this now. A quick question about the "distinct" comment though...is the feeling that sqlite does not support the distinct syntax thus forcing the skips?

**Comment by thraxil** [comment]
`.distinct()` works with SQLite, but `.distinct('some_column')` is PostgreSQL only: https://docs.djangoproject.com/en/dev/ref/models/querysets/#distinct

**Comment by nikolas** [comment]
In any case, I don't need `.distinct()` anymore, since I can search for right-most node using django-treebeard's `MP_Node.path` attribute, which requires less work than what I was doing before. Because all the tests are running in both databases (tested with `make travis` and `make jenkins`), I removed all the skips.

**Comment by sdreher** [comment]
Cool. Thanks for the clarification.

**Comment by sdreher** [comment]
On an invalid form submit, the labels for "next new session" and "last completed activity" are disappearing. Example is for a brand-new participant.

screen shot 2015-04-23 at 10 49 03 am

**Comment by nikolas** [comment]
Oh yeah.. that will break on the validation view because that's generated with javascript. I'll commit a fix for that in a second.

**Comment by nikolas** [comment]
Thanks for catching that @sdreher, I just committed a fix.

**Pull request merged**
